version: '3.8'

services:

  redis:
    image: redis:7-alpine
#    command: redis-server --requirepass "${REDIS_PASSWORD}"
    env_file:
      - ../.env

#  bot:
#    build:
#      context: ../telegram_bot
#    env_file:
#      - ../.env
#    restart: always
#    volumes:
#      - ../telegram_bot:/app
#    depends_on:
#      - redis
